### ISSUE TITLE
error when variable comment-start-skip is nil

### ISSUE THREAD

**Issue by BlindingDark** [alezost/mwim.el#12]
linux emacs 26.1

In some case, variable `comment-start-skip` is nil, call `mwim-line-comment-text-beginning` will cause error `wrong-type-argument stringp nil`.

because `mwim-line-comment-text-beginning` called `comment-search-forward`

```elisp
(defun mwim-line-comment-text-beginning ()
  (save-excursion
    (goto-char (line-beginning-position))
    (let ((beg (comment-search-forward (line-end-position) t)))
      (when beg (point)))))
```
and then

```elisp
(defun comment-search-forward (limit &optional noerror)
    ...
    (if (looking-at comment-start-skip) ;; comment-start-skip is nil!
	...)
```

---

workaround

```elisp
(defun mwim-line-comment-text-beginning ()
  (save-excursion
    (goto-char (line-beginning-position))
    (if comment-start-skip ;; if comment-start-skip not nil
        (let ((beg (comment-search-forward (line-end-position) t)))
          (when beg (point))))))
```

Or is there any better suggestion?

**Comment by alezost** [comment]
Hello, I'm very sorry for the huge delay, I missed this issue :blush:

I am aware of this problem (I even "fixed" `sql-mode` in my [emacs config](https://github.com/alezost/emacs-config/commit/a918dc4db91222a2776b0684a15e627fc4b8c4a0) as it does not set `comment-start-skip`).  And although I think it should better be fixed in Emacs itself (I think `comment-search-forward` should handle this error case), I agree that a workaround on mwim side is better than the current unhandled error.

The workaround is committed as b4f3edb4c0fb8f8b71cecbf8095c2c25a8ffbf85.  Thank you!
