### ISSUE TITLE
mwim-beginning/end-of-code-or-line on wrapped line

### ISSUE THREAD

**Issue by 4d47** [alezost/mwim.el#4]
`mwim-beginning-of-code-or-line` and `mwim-end-of-code-or-line` don't move well on virtual lines.

```
1    sa asdkj asdkfj asdfjaskdlfj asdf ↩
2  ↪ asdfjaksdfjkasdfjka | sdfaksdfjkf ↩
3  ↪ adsflkj asdfkjsdf
```

For example, when on middle of second line:
`mwim-beginning-of-code-or-line` will move at beginning of line 2 then stay there.
`mwim-end-of-code-or-line` will go at beginning of line 3 then end of line 3.

I believe it should be:
`mwim-beginning-of-code-or-line` move at beginning of line 2 then beginning of line 1.
`mwim-end-of-code-or-line` move at end of line 2 then end of line 3.

The (code-or-line) part is working well, just the moving past the bent arrows.

**Comment by alezost** [comment]
Hello!

```
mwim-beginning-of-code-or-line and mwim-end-of-code-or-line don't move well on virtual lines.
```

I suppose you mean `visual-line-mode`, right?

```
For example, when on middle of second line:
mwim-beginning-of-code-or-line will move at beginning of line 2 then stay there.
mwim-end-of-code-or-line will go at beginning of line 3 then end of line 3.
```

I can't reproduce this.  For me, `mwim-beginning-of-code-or-line` moves
to the beginning of line 2 as you say, but `mwim-end-of-code-or-line`
moves to the end of line 2.  And this is exactly what I expect.

Actually where the point is moved is defined by
`mwim-beginning-of-line-function` and `mwim-end-of-line-function`
variables: `beginning/end-of-visual-line` are the default values for
these variables, but you can set them to other functions, for example to
`beginning/end-of-line` (which is probably not what you want).

```
I believe it should be:
mwim-beginning-of-code-or-line move at beginning of line 2 then beginning of line 1.
mwim-end-of-code-or-line move at end of line 2 then end of line 3.
```

This is an interesting proposal, but I don't think it should be so: if
we are talking about visual lines, then beginning of line and beginning
of code here is the same point in the beginning of this visual line, so
the point just should move and stay there.  The same for the end of line
or code.

Returning to the problem you faced with `mwim-end-of-code-or-line`,
perhaps the problem is actually in `end-of-visual-line` function.  Try
`M-x end-of-visual-line`, does it move the point where you expect?

**Comment by 4d47** [comment]
Thank you for the help!

Yes it's same when I try `M-x end-of-visual-line`.

Okay I think I better understand my problem.
I did `emacs --no-init` then `M-x global-visual-line-mode`.
Added this in *scratch* 

```
sha512-qzrZqY/kMVCEYeu/gCm8U2800Wz++LTGK4pitW/iswpCbjwxhsmUwleL1YXaHImptCHG0vJwU7Ly7ROw3ZQoww==
```

and made the frame small enough for the line to wrap.
From beginning of line typed `C-e` multiple times until it reach the end of physical line.
Then type multile times `C-a`.

Somehow I was expecting it returns to beginning of physical line.
